# This is for https://github.com/yanconglin/ICP-Flow?tab=readme-ov-file

FROM nvidia/cuda:11.6.1-cudnn8-devel-ubuntu20.04
SHELL ["/bin/bash", "-c"]

# -----------------------------
# 1. 安裝基本套件
# -----------------------------
    RUN apt update && \
    apt install -y wget curl gnupg lsb-release vim python3-pip sudo cmake git libgl1 ninja && \
    apt clean && rm -rf /var/lib/apt/lists/*

# -----------------------------
# 2. 建立使用者 user
# -----------------------------
RUN groupadd -g 1000 user && \
useradd -m -u 1000 -g 1000 -s /bin/bash user && \
usermod -aG sudo user && \
echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/user && \
chmod 0440 /etc/sudoers.d/user

# ----------------------------
# 3. 安裝 Miniconda
# ----------------------------- 
ENV CONDA_DIR=/home/user/miniconda3
RUN mkdir -p $CONDA_DIR && \
    wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -u -p $CONDA_DIR && \
    rm /tmp/miniconda.sh

# -----------------------------
# 4. 設定 Conda
# -----------------------------
ENV PATH=$CONDA_DIR/bin:$PATH
RUN echo '# Set conda env' >> /home/user/.bashrc && \
    echo '. $CONDA_DIR/etc/profile.d/conda.sh' >> /home/user/.bashrc && \
    echo 'conda activate base' >> /home/user/.bashrc && \
    echo 'auto_activate_base: true' > /home/user/.condarc && \
    echo 'changeps1: false' >> /home/user/.condarc
    
# -----------------------------
# 5. 設定 shell 
# -----------------------------
RUN echo '# Set container prompt' >> /home/user/.bashrc && \
    echo 'export PS1="(container) $PS1"' >> /home/user/.bashrc && \    
    chown -R user:user /home/user

# -----------------------------
# 6. 設定預設執行環境
# -----------------------------
ENV TERM xterm-256color
USER user

WORKDIR /
CMD ["bash"]